### ISSUE TITLE
статичні файли

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-lists#1]
https://github.com/DenisPitsul/react-lists/blob/fc6a731f1cc1d516b9e85076a683634f7602d3ed/src/components/UserList/index.jsx#L11
- в посиланнях на статичні файли не вказують 'public', ця папка ніби і є вже рутом:

> You should always reference public assets using root absolute path - for example, `public/icon.png` should be referenced in source code as `/icon.png`

 ([джерело](https://vitejs.dev/guide/assets.html#the-public-directory))

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-lists/commit/82d91c5cd47cca9fbc14589d083a43c2958494b2
