### ISSUE TITLE
порядок імпортів

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-lists#2]
https://github.com/DenisPitsul/react-lists/blob/fc6a731f1cc1d516b9e85076a683634f7602d3ed/src/components/UserList/UserListItem/index.jsx#L1-L4
- прийнято спочатку вказувати бібліотечні імпорти, потім локальні

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-lists/commit/82d91c5cd47cca9fbc14589d083a43c2958494b2
