### ISSUE TITLE
розмітка

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-lists#3]
https://github.com/DenisPitsul/react-lists/blob/fc6a731f1cc1d516b9e85076a683634f7602d3ed/src/components/UserList/UserListItem/UserListItem.module.css#L19
- за рахунок того, що підсвітка зроблена бордером, то розмітка "стрибає" коли додаєш/прибираєш підсвітку. Треба або мати прозору границю, яка буде отримувати колір при виборі, або використовувати щось, що не формує розміри елемента, типу тіні або outline

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-lists/commit/6f7d78636d9ae22473b3257a2bbe21d15048ac80
